package lt.vu.mif.MyBatis.Mappers;

import java.util.List;
import lt.vu.mif.MyBatis.ViewModels.Cars;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    int insert(Cars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    Cars selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    List<Cars> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CARS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    int updateByPrimaryKey(Cars record);
}