package lt.vu.mif.MyBatis.Mappers;

import java.util.List;
import lt.vu.mif.MyBatis.ViewModels.Shops;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ShopsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    int insert(Shops record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    Shops selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    List<Shops> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOPS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    int updateByPrimaryKey(Shops record);
}