package lt.vu.mif.MyBatis.ViewModels;

import java.util.ArrayList;
import java.util.List;

public class Drivers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVERS.ID
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVERS.NAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DRIVERS.SURNAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    private String surname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVERS.ID
     *
     * @return the value of PUBLIC.DRIVERS.ID
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVERS.ID
     *
     * @param id the value for PUBLIC.DRIVERS.ID
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVERS.NAME
     *
     * @return the value of PUBLIC.DRIVERS.NAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVERS.NAME
     *
     * @param name the value for PUBLIC.DRIVERS.NAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DRIVERS.SURNAME
     *
     * @return the value of PUBLIC.DRIVERS.SURNAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public String getSurname() {
        return surname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DRIVERS.SURNAME
     *
     * @param surname the value for PUBLIC.DRIVERS.SURNAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    public List<Cars> cars = new ArrayList<>();
    public List<Cars> getCars() {return this.cars;}
    public void setCars(List<Cars> cars) { this.cars = cars;}
}