package lt.vu.mif.MyBatis.ViewModels;

import java.util.List;

public class Shops {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPS.ID
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPS.ADDRESS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SHOPS.NAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOPS.ID
     *
     * @return the value of PUBLIC.SHOPS.ID
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOPS.ID
     *
     * @param id the value for PUBLIC.SHOPS.ID
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOPS.ADDRESS
     *
     * @return the value of PUBLIC.SHOPS.ADDRESS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOPS.ADDRESS
     *
     * @param address the value for PUBLIC.SHOPS.ADDRESS
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SHOPS.NAME
     *
     * @return the value of PUBLIC.SHOPS.NAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SHOPS.NAME
     *
     * @param name the value for PUBLIC.SHOPS.NAME
     *
     * @mbg.generated Wed Apr 18 13:58:42 EEST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    public List<Cars> cars;
    public List<Cars> getCars() {return this.cars;}
    public void setCars(List<Cars> cars) {this.cars = cars;}
}